# Site settings
head_title: Full-Stack and Mobile Developer | Herycklys
title: Herycklys Gonçalves
email:
url: herycklys.dev
description: "Full-Stack & Mobile Developer expert in Javascript, Golang, PHP, React | Herycklys"
keywords: "Software Development, Javascript, WordPress, NodeJS, AWB, Full-stack developer"
skills: "Full-Stack and Mobile Developer"
meta_author: Gonçalves Herycklys

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Herycklys Gonçalves
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/Herycklys

# Postal address (add as many lines as necessary)
address:
  - line: São Paulo - Brazil

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
